### ISSUE TITLE
Desenhando arquitetura de Stream de dados e Roadmap

### ISSUE THREAD

**Issue by EduardoGurgel** [ResidenciaTICBrisa/04_PipelineTCU#41]
# Descrição
A arquitetura de stream de dados é uma proposta de solução para o nosso projeto, em que possibilita a análise e processamento de dados em tempo real. Possibilitando que as organizações tomem decisões mais informadas e estratégicas, além de oferecer insights valiosos para melhorar a eficiência operacional.

# Tarefas

- [x] Concluir a pesquisa de mercado
- [x] Desenhar a arquitetura
- [x] Adicionar ao gitpages
- [x] Validar com o cliente

**Comment by EduardoGurgel** [comment]
Finalizado!
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/51385738/479a7e61-8698-496e-b6b2-be28b14230ab)
