### ISSUE TITLE
Desenhar o roadmap do projeto

### ISSUE THREAD

**Issue by EduardoGurgel** [ResidenciaTICBrisa/04_PipelineTCU#53]
# Descrição
Realizar o desenho do roadmap do projeto até a entrega final

# Tarefas

- [x] Desenhar o roadmap interativo, possibilitando alterações
- [x] Dividir por sprint
- [x] Possuir deadlines importantes
- [x] Atribuir atividade de cada membro

# Critérios de Aceitação
O que foi concluído até o momento.
- [x] Link disponibilizado
- [x] Documentar no gitpages

**Comment by EduardoGurgel** [comment]
Link disponível:
https://miro.com/app/board/uXjVMvYd-MQ=/?share_link_id=66767367565

**Comment by EduardoGurgel** [comment]
Finalizado!
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/51385738/14e9c09d-f90d-41e7-8621-0cf4f39c2958)
